// <auto-generated />
using System;
using HeThongTimViec.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HETHONGTIMVIEC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250427102253_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HeThongTimViec.Models.BaoCaoViPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminXuLyId")
                        .HasColumnType("int");

                    b.Property<string>("ChiTiet")
                        .HasColumnType("longtext");

                    b.Property<string>("GhiChuAdmin")
                        .HasColumnType("longtext");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayBaoCao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NguoiBaoCaoId")
                        .HasColumnType("int");

                    b.Property<int>("TinTuyenDungId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiXuLy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("moi");

                    b.HasKey("Id");

                    b.HasIndex("AdminXuLyId");

                    b.HasIndex("NguoiBaoCaoId");

                    b.HasIndex("TinTuyenDungId");

                    b.ToTable("BaoCaoViPham");
                });

            modelBuilder.Entity("HeThongTimViec.Models.DiaDiemMongMuon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("QuanHuyenId")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuanHuyenId");

                    b.HasIndex("ThanhPhoId");

                    b.HasIndex("NguoiDungId", "QuanHuyenId")
                        .IsUnique()
                        .HasDatabaseName("uq_NguoiDung_DiaDiem");

                    b.ToTable("DiaDiemMongMuon");
                });

            modelBuilder.Entity("HeThongTimViec.Models.HoSoDoanhNghiep", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int?>("AdminXacMinhId")
                        .HasColumnType("int");

                    b.Property<bool>("DaXacMinh")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DiaChiDangKy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayXacMinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("QuyMoCongTy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UrlLogo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UrlWebsite")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("NguoiDungId");

                    b.HasIndex("AdminXacMinhId");

                    b.HasIndex("MaSoThue")
                        .IsUnique();

                    b.ToTable("HoSoDoanhNghiep");
                });

            modelBuilder.Entity("HeThongTimViec.Models.HoSoUngVien", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<bool>("ChoPhepTimKiem")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GioiThieuBanThan")
                        .HasColumnType("longtext");

                    b.Property<string>("LoaiLuongMongMuon")
                        .HasColumnType("longtext");

                    b.Property<ulong?>("MucLuongMongMuon")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("TieuDeHoSo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrangThaiTimViec")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("dangtimtichcuc");

                    b.Property<string>("UrlCvMacDinh")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ViTriMongMuon")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("NguoiDungId");

                    b.ToTable("HoSoUngVien");
                });

            modelBuilder.Entity("HeThongTimViec.Models.LichLamViecCongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuoiLamViec")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan?>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("NgayTrongTuan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TinTuyenDungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TinTuyenDungId");

                    b.ToTable("LichLamViecCongViec");
                });

            modelBuilder.Entity("HeThongTimViec.Models.LichRanhUngVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuoiLamViec")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NgayTrongTuan")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId", "NgayTrongTuan", "BuoiLamViec")
                        .IsUnique()
                        .HasDatabaseName("uq_NguoiDung_LichRanh");

                    b.ToTable("LichRanhUngVien");
                });

            modelBuilder.Entity("HeThongTimViec.Models.NganhNghe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Ten")
                        .IsUnique();

                    b.ToTable("NganhNghe");
                });

            modelBuilder.Entity("HeThongTimViec.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiChiTiet")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LoaiTk")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("QuanHuyenId")
                        .HasColumnType("int");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ThanhPhoId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiTk")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("kichhoat");

                    b.Property<string>("UrlAvatar")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("QuanHuyenId");

                    b.HasIndex("Sdt")
                        .IsUnique();

                    b.HasIndex("ThanhPhoId");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("HeThongTimViec.Models.QuanHuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ThanhPhoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThanhPhoId", "Ten")
                        .IsUnique()
                        .HasDatabaseName("uq_QuanHuyen_ThanhPho");

                    b.ToTable("QuanHuyen");
                });

            modelBuilder.Entity("HeThongTimViec.Models.ThanhPho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Ten")
                        .IsUnique();

                    b.ToTable("ThanhPho");
                });

            modelBuilder.Entity("HeThongTimViec.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DuLieu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdLienQuan")
                        .HasColumnType("int");

                    b.Property<string>("LoaiLienQuan")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("NgayDoc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("HeThongTimViec.Models.TinDaLuu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayLuu")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("TinTuyenDungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TinTuyenDungId");

                    b.HasIndex("NguoiDungId", "TinTuyenDungId")
                        .IsUnique()
                        .HasDatabaseName("uq_NguoiDung_TinDaLuu");

                    b.ToTable("TinDaLuu");
                });

            modelBuilder.Entity("HeThongTimViec.Models.TinNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("NgayDoc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NguoiGuiId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiNhanId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TinLienQuanId")
                        .HasColumnType("int");

                    b.Property<int?>("UngTuyenLienQuanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiGuiId");

                    b.HasIndex("NguoiNhanId");

                    b.HasIndex("TinLienQuanId");

                    b.HasIndex("UngTuyenLienQuanId");

                    b.ToTable("TinNhan");
                });

            modelBuilder.Entity("HeThongTimViec.Models.TinTuyenDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminDuyetId")
                        .HasColumnType("int");

                    b.Property<string>("DiaChiLamViec")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoaiHinhCongViec")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LoaiLuong")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong?>("LuongToiDa")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("LuongToiThieu")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NguoiDangId")
                        .HasColumnType("int");

                    b.Property<int>("QuanHuyenId")
                        .HasColumnType("int");

                    b.Property<string>("QuyenLoi")
                        .HasColumnType("longtext");

                    b.Property<int>("SoLuongTuyen")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhoId")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("TinGap")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("choduyet");

                    b.Property<string>("YeuCau")
                        .HasColumnType("longtext");

                    b.Property<string>("YeuCauHocVanText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("YeuCauKinhNghiemText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdminDuyetId");

                    b.HasIndex("NguoiDangId");

                    b.HasIndex("QuanHuyenId");

                    b.HasIndex("ThanhPhoId");

                    b.ToTable("TinTuyenDung");
                });

            modelBuilder.Entity("HeThongTimViec.Models.TinTuyenDung_NganhNghe", b =>
                {
                    b.Property<int>("TinTuyenDungId")
                        .HasColumnType("int");

                    b.Property<int>("NganhNgheId")
                        .HasColumnType("int");

                    b.HasKey("TinTuyenDungId", "NganhNgheId");

                    b.HasIndex("NganhNgheId");

                    b.ToTable("TinTuyenDung_NganhNghe");
                });

            modelBuilder.Entity("HeThongTimViec.Models.UngTuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("NgayCapNhatTrangThai")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ThuGioiThieu")
                        .HasColumnType("longtext");

                    b.Property<int>("TinTuyenDungId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("danop");

                    b.Property<int>("UngVienId")
                        .HasColumnType("int");

                    b.Property<string>("UrlCvDaNop")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UngVienId");

                    b.HasIndex("TinTuyenDungId", "UngVienId")
                        .IsUnique()
                        .HasDatabaseName("uq_TinTuyenDung_UngVien");

                    b.ToTable("UngTuyen");
                });

            modelBuilder.Entity("HeThongTimViec.Models.BaoCaoViPham", b =>
                {
                    b.HasOne("HeThongTimViec.Models.NguoiDung", "AdminXuLy")
                        .WithMany("BaoCaoViPhamDaXuLy")
                        .HasForeignKey("AdminXuLyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeThongTimViec.Models.NguoiDung", "NguoiBaoCao")
                        .WithMany("BaoCaoViPhamsDaGui")
                        .HasForeignKey("NguoiBaoCaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongTimViec.Models.TinTuyenDung", "TinTuyenDung")
                        .WithMany("BaoCaoViPhams")
                        .HasForeignKey("TinTuyenDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminXuLy");

                    b.Navigation("NguoiBaoCao");

                    b.Navigation("TinTuyenDung");
                });

            modelBuilder.Entity("HeThongTimViec.Models.DiaDiemMongMuon", b =>
                {
                    b.HasOne("HeThongTimViec.Models.NguoiDung", "NguoiDung")
                        .WithMany("DiaDiemMongMuons")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongTimViec.Models.QuanHuyen", "QuanHuyen")
                        .WithMany("DiaDiemMongMuons")
                        .HasForeignKey("QuanHuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongTimViec.Models.ThanhPho", "ThanhPho")
                        .WithMany("DiaDiemMongMuons")
                        .HasForeignKey("ThanhPhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("QuanHuyen");

                    b.Navigation("ThanhPho");
                });

            modelBuilder.Entity("HeThongTimViec.Models.HoSoDoanhNghiep", b =>
                {
                    b.HasOne("HeThongTimViec.Models.NguoiDung", "AdminXacMinh")
                        .WithMany("HoSoDoanhNghiepDaXacMinh")
                        .HasForeignKey("AdminXacMinhId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeThongTimViec.Models.NguoiDung", "NguoiDung")
                        .WithOne("HoSoDoanhNghiep")
                        .HasForeignKey("HeThongTimViec.Models.HoSoDoanhNghiep", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminXacMinh");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HeThongTimViec.Models.HoSoUngVien", b =>
                {
                    b.HasOne("HeThongTimViec.Models.NguoiDung", "NguoiDung")
                        .WithOne("HoSoUngVien")
                        .HasForeignKey("HeThongTimViec.Models.HoSoUngVien", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HeThongTimViec.Models.LichLamViecCongViec", b =>
                {
                    b.HasOne("HeThongTimViec.Models.TinTuyenDung", "TinTuyenDung")
                        .WithMany("LichLamViecCongViecs")
                        .HasForeignKey("TinTuyenDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinTuyenDung");
                });

            modelBuilder.Entity("HeThongTimViec.Models.LichRanhUngVien", b =>
                {
                    b.HasOne("HeThongTimViec.Models.NguoiDung", "NguoiDung")
                        .WithMany("LichRanhUngViens")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HeThongTimViec.Models.NguoiDung", b =>
                {
                    b.HasOne("HeThongTimViec.Models.QuanHuyen", "QuanHuyen")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("QuanHuyenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeThongTimViec.Models.ThanhPho", "ThanhPho")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("ThanhPhoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("QuanHuyen");

                    b.Navigation("ThanhPho");
                });

            modelBuilder.Entity("HeThongTimViec.Models.QuanHuyen", b =>
                {
                    b.HasOne("HeThongTimViec.Models.ThanhPho", "ThanhPho")
                        .WithMany("QuanHuyens")
                        .HasForeignKey("ThanhPhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhPho");
                });

            modelBuilder.Entity("HeThongTimViec.Models.ThongBao", b =>
                {
                    b.HasOne("HeThongTimViec.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongBaos")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HeThongTimViec.Models.TinDaLuu", b =>
                {
                    b.HasOne("HeThongTimViec.Models.NguoiDung", "NguoiDung")
                        .WithMany("TinDaLuus")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongTimViec.Models.TinTuyenDung", "TinTuyenDung")
                        .WithMany("TinDaLuus")
                        .HasForeignKey("TinTuyenDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("TinTuyenDung");
                });

            modelBuilder.Entity("HeThongTimViec.Models.TinNhan", b =>
                {
                    b.HasOne("HeThongTimViec.Models.NguoiDung", "NguoiGui")
                        .WithMany("TinNhansDaGui")
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongTimViec.Models.NguoiDung", "NguoiNhan")
                        .WithMany("TinNhansDaNhan")
                        .HasForeignKey("NguoiNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongTimViec.Models.TinTuyenDung", "TinLienQuan")
                        .WithMany("TinNhansLienQuan")
                        .HasForeignKey("TinLienQuanId");

                    b.HasOne("HeThongTimViec.Models.UngTuyen", "UngTuyenLienQuan")
                        .WithMany("TinNhansLienQuan")
                        .HasForeignKey("UngTuyenLienQuanId");

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");

                    b.Navigation("TinLienQuan");

                    b.Navigation("UngTuyenLienQuan");
                });

            modelBuilder.Entity("HeThongTimViec.Models.TinTuyenDung", b =>
                {
                    b.HasOne("HeThongTimViec.Models.NguoiDung", "AdminDuyet")
                        .WithMany("TinTuyenDungDaDuyet")
                        .HasForeignKey("AdminDuyetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeThongTimViec.Models.NguoiDung", "NguoiDang")
                        .WithMany("TinTuyenDungsDaDang")
                        .HasForeignKey("NguoiDangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongTimViec.Models.QuanHuyen", "QuanHuyen")
                        .WithMany("TinTuyenDungs")
                        .HasForeignKey("QuanHuyenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongTimViec.Models.ThanhPho", "ThanhPho")
                        .WithMany("TinTuyenDungs")
                        .HasForeignKey("ThanhPhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminDuyet");

                    b.Navigation("NguoiDang");

                    b.Navigation("QuanHuyen");

                    b.Navigation("ThanhPho");
                });

            modelBuilder.Entity("HeThongTimViec.Models.TinTuyenDung_NganhNghe", b =>
                {
                    b.HasOne("HeThongTimViec.Models.NganhNghe", "NganhNghe")
                        .WithMany("TinTuyenDungNganhNghes")
                        .HasForeignKey("NganhNgheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongTimViec.Models.TinTuyenDung", "TinTuyenDung")
                        .WithMany("TinTuyenDungNganhNghes")
                        .HasForeignKey("TinTuyenDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NganhNghe");

                    b.Navigation("TinTuyenDung");
                });

            modelBuilder.Entity("HeThongTimViec.Models.UngTuyen", b =>
                {
                    b.HasOne("HeThongTimViec.Models.TinTuyenDung", "TinTuyenDung")
                        .WithMany("UngTuyens")
                        .HasForeignKey("TinTuyenDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongTimViec.Models.NguoiDung", "UngVien")
                        .WithMany("UngTuyens")
                        .HasForeignKey("UngVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinTuyenDung");

                    b.Navigation("UngVien");
                });

            modelBuilder.Entity("HeThongTimViec.Models.NganhNghe", b =>
                {
                    b.Navigation("TinTuyenDungNganhNghes");
                });

            modelBuilder.Entity("HeThongTimViec.Models.NguoiDung", b =>
                {
                    b.Navigation("BaoCaoViPhamDaXuLy");

                    b.Navigation("BaoCaoViPhamsDaGui");

                    b.Navigation("DiaDiemMongMuons");

                    b.Navigation("HoSoDoanhNghiep");

                    b.Navigation("HoSoDoanhNghiepDaXacMinh");

                    b.Navigation("HoSoUngVien");

                    b.Navigation("LichRanhUngViens");

                    b.Navigation("ThongBaos");

                    b.Navigation("TinDaLuus");

                    b.Navigation("TinNhansDaGui");

                    b.Navigation("TinNhansDaNhan");

                    b.Navigation("TinTuyenDungDaDuyet");

                    b.Navigation("TinTuyenDungsDaDang");

                    b.Navigation("UngTuyens");
                });

            modelBuilder.Entity("HeThongTimViec.Models.QuanHuyen", b =>
                {
                    b.Navigation("DiaDiemMongMuons");

                    b.Navigation("NguoiDungs");

                    b.Navigation("TinTuyenDungs");
                });

            modelBuilder.Entity("HeThongTimViec.Models.ThanhPho", b =>
                {
                    b.Navigation("DiaDiemMongMuons");

                    b.Navigation("NguoiDungs");

                    b.Navigation("QuanHuyens");

                    b.Navigation("TinTuyenDungs");
                });

            modelBuilder.Entity("HeThongTimViec.Models.TinTuyenDung", b =>
                {
                    b.Navigation("BaoCaoViPhams");

                    b.Navigation("LichLamViecCongViecs");

                    b.Navigation("TinDaLuus");

                    b.Navigation("TinNhansLienQuan");

                    b.Navigation("TinTuyenDungNganhNghes");

                    b.Navigation("UngTuyens");
                });

            modelBuilder.Entity("HeThongTimViec.Models.UngTuyen", b =>
                {
                    b.Navigation("TinNhansLienQuan");
                });
#pragma warning restore 612, 618
        }
    }
}
